--Criação Tabelas
CREATE TABLE TB_CLIENTE(
  CPF       VARCHAR2(11),
  NOME      VARCHAR2(80) NOT NULL,
  UF        VARCHAR2(2) NOT NULL,
  CELULAR   VARCHAR(10) NOT NULL,
  CONSTRAINT PK_TB_USUARIO PRIMARY KEY (CPF)
);

CREATE TABLE TB_FINANCIAMENTO(
 ID_FINANCIAMENTO          INTEGER,
 CPF                       VARCHAR2(11),
 TIPO_FINANCIAMENTO        VARCHAR2(20) NOT NULL,
 VALOR_TOTAL               NUMBER(12,2) NOT NULL,
 DATA_ULTIMO_VENCIMENTO    DATE NOT NULL,
 CONSTRAINT PK_TB_FINANCIAMENTO PRIMARY KEY (ID_FINANCIAMENTO),
 CONSTRAINT FK1_TB_FINANCIAMENTO FOREIGN KEY (CPF) REFERENCES TB_CLIENTE(CPF)
);

CREATE TABLE TB_PARCELAFINANCIAMENTO(
  ID_FINANCIAMENTO               INTEGER,
  NUMERO_PARCELA                 INTEGER,
  VALOR_PARCELA                  NUMBER(12,2) NOT NULL,
  DATA_VENCIMENTO                DATE NOT NULL,
  DATE_PAGAMENTO                 DATE,
  CONSTRAINT PK_TB_PARCELAFINANCIAMENTO PRIMARY KEY (ID_FINANCIAMENTO,NUMERO_PARCELA),
  CONSTRAINT FK1_TB_PARCELAFINANCIAMENTO FOREIGN KEY (ID_FINANCIAMENTO) REFERENCES TB_FINANCIAMENTO(ID_FINANCIAMENTO)
);
-- Inserir Clientes
BEGIN
  
  FOR numero IN 1..20 LOOP
    IF(numero <= 10) THEN
        INSERT INTO TB_CLIENTE
        (CPF,NOME, UF, CELULAR)
        VALUES
        ('000000000' || LPAD(numero,2,0),'Cliente ' || LPAD(numero,2,0), 'SP','9999999' || LPAD(numero,2,0));   
    ELSE
        INSERT INTO TB_CLIENTE
        (CPF,NOME, UF, CELULAR)
        VALUES
        ('000000000' || LPAD(numero,2,0),'Cliente ' || LPAD(numero,2,0), 'MG','9999999' || LPAD(numero,2,0));
    END IF;
     
  END LOOP;
  
  COMMIT;
  
  FOR 
end;

-- Financiamentos
INSERT INTO TB_FINANCIAMENTO
(ID_FINANCIAMENTO,CPF,TIPO_FINANCIAMENTO,VALOR_TOTAL,DATA_ULTIMO_VENCIMENTO)
VALUES
(1,'00000000001','CONSIGNADO',1715.45,'10NOV2022');

INSERT INTO TB_FINANCIAMENTO
(ID_FINANCIAMENTO,CPF,TIPO_FINANCIAMENTO,VALOR_TOTAL,DATA_ULTIMO_VENCIMENTO)
VALUES
(2,'00000000011','CONSIGNADO',1150.5,'10NOV2022');

-- Parcelas
-- Id 1
BEGIN
  
  FOR numero IN 1..11 LOOP
    IF(numero <= 10) THEN
        INSERT INTO tb_PARCELAFINANCIAMENTO
        (ID_FINANCIAMENTO,NUMERO_PARCELA,VALOR_PARCELA,DATA_VENCIMENTO,DATE_PAGAMENTO)
        VALUES
        (1,numero,155.95,TO_DATE('10/'|| LPAD(numero,2,0) || '/2022'  ,'DD/MM/YYYY'),TO_DATE('10/'|| TO_CHAR(LPAD(numero,2,0)) || '/2022','DD/MM/YYYY'));
    ELSE
        INSERT INTO tb_PARCELAFINANCIAMENTO
        (ID_FINANCIAMENTO,NUMERO_PARCELA,VALOR_PARCELA,DATA_VENCIMENTO,DATE_PAGAMENTO)
        VALUES
        (1,numero,155.95,TO_DATE('10/'|| LPAD(numero,2,0) || '/2022'  ,'DD/MM/YYYY'),NULL);
        
    END IF;
  END LOOP;
  
END
--2
--Id 2
BEGIN
  
  FOR numero IN 1..11 LOOP
    IF(numero <= 10) THEN
        INSERT INTO tb_PARCELAFINANCIAMENTO
        (ID_FINANCIAMENTO,NUMERO_PARCELA,VALOR_PARCELA,DATA_VENCIMENTO,DATE_PAGAMENTO)
        VALUES
        (2,numero,100.50,TO_DATE('10/'|| LPAD(numero,2,0) || '/2022'  ,'DD/MM/YYYY'),TO_DATE('10/'|| TO_CHAR(LPAD(numero,2,0)) || '/2022','DD/MM/YYYY'));
    ELSE
        INSERT INTO tb_PARCELAFINANCIAMENTO
        (ID_FINANCIAMENTO,NUMERO_PARCELA,VALOR_PARCELA,DATA_VENCIMENTO,DATE_PAGAMENTO)
        VALUES
        (2,numero,100.50,TO_DATE('10/'|| LPAD(numero,2,0) || '/2022'  ,'DD/MM/YYYY'),NULL);
        
    END IF;
  END LOOP;
  
end;


--Querys

--1 60% PARCELAS PAGAS
SELECT A.NOME, A.UF, B.VALOR_TOTAL,SUM(DECODE(DATE_PAGAMENTO,NULL,0,VALOR_PARCELA)) VALOR_PAGO,(SUM(DECODE(DATE_PAGAMENTO,NULL,0,VALOR_PARCELA)) * 100 / B.VALOR_TOTAL)  PORCENTAGEM_PAGA
  FROM TB_CLIENTE A,
       TB_FINANCIAMENTO B,
       tb_PARCELAFINANCIAMENTO C
WHERE A.CPF = B.CPF
  AND B.ID_FINANCIAMENTO = C.ID_FINANCIAMENTO
  AND A.UF = 'SP'
GROUP BY A.NOME, A.UF, B.VALOR_TOTAL
HAVING (SUM(DECODE(DATE_PAGAMENTO,NULL,0,VALOR_PARCELA)) * 100 / B.VALOR_TOTAL) >= 60;


--2
-- Vencidos a mais de 5 dias
SELECT A.*,TRUNC(SYSDATE)-A.DATA_VENCIMENTO QTDE_DIAS_VENCIMENTO
  FROM TB_PARCELAFINANCIAMENTO A
 WHERE A.DATA_VENCIMENTO <= SYSDATE
   AND A.DATE_PAGAMENTO IS NULL
   AND TRUNC(SYSDATE)-A.DATA_VENCIMENTO > 5;

-- 4 Primeiros clientes vencidos a mais de 5
SELECT C.CPF, C.NOME, C.UF, C.CELULAR
  FROM TB_CLIENTE C,
       TB_FINANCIAMENTO B
 WHERE C.CPF = B.CPF
   AND EXISTS(
      SELECT 1
        FROM TB_PARCELAFINANCIAMENTO A
       WHERE A.DATA_VENCIMENTO <= SYSDATE
         AND A.DATE_PAGAMENTO IS NULL
         AND TRUNC(SYSDATE)-A.DATA_VENCIMENTO > 5
         AND A.ID_FINANCIAMENTO = B.ID_FINANCIAMENTO)
    AND ROWNUM < 5
  GROUP BY C.CPF, C.NOME, C.UF, C.CELULAR;


